version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      # for v23: client version 1.42 is too new. Maximum supported API version is 1.41
      - dependency-name: "github.com/docker/docker"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "feat"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "feat"
      include: "scope"
