# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: pretty-format-json
        args: [--autofix, --no-sort-keys, --indent=4]
- repo: https://github.com/golangci/golangci-lint
  rev: v1.51.2
  hooks:
    -   id: golangci-lint
        args: [--disable=errcheck]
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
    -   id: commitizen
        stages: [commit-msg]
