language: go
git:
  depth: false
go:
  - 1.17
services:
  - docker
script:
  - go test ./...
  - curl -sfL https://git.io/goreleaser | sh -s -- build --rm-dist --single-target --snapshot --output ./vulcan-local
  - docker build . -t vulcan-local
  - ./script/test.sh
after_success:
  - test -n "$TRAVIS_TAG" && docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
deploy:
  - provider: script
    cleanup: false
    script: curl -sfL https://git.io/goreleaser | sh -s --
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
