language: go
go:
  - 1.19.x
services:
  - docker
before_script: go install github.com/goreleaser/goreleaser@v1.19.1
script:
  - go test ./...
  - goreleaser build --clean --single-target --snapshot --output ./vulcan-local
  - docker build . -t vulcan-local
  - ./script/test.sh
after_success:
  - test -n "$TRAVIS_TAG" && docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
deploy:
  - provider: script
    cleanup: false
    script: goreleaser
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
