language: go
go:
  - 1.19.x
services:
  - docker
script:
  - go test ./...
  - curl -sfL https://git.io/goreleaser | VERSION=v1.19.1 bash -s -- build --clean --single-target --snapshot --output ./vulcan-local
  - docker build . -t vulcan-local
  - ./script/test.sh
after_success:
  - test -n "$TRAVIS_TAG" && docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
deploy:
  - provider: script
    cleanup: false
    script: curl -sfL https://goreleaser.com/static/run | VERSION=v1.19.1 bash -s --
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
