#!/bin/sh

# Copyright 2021 Adevinta

set -e

TAR_FILE="$(mktemp)"
RELEASES_URL="https://github.com/adevinta/vulcan-local/releases"
test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"

last_version() {
  curl -sL -o /dev/null -w "%{url_effective}" "$RELEASES_URL/latest" | 
    rev | 
    cut -f1 -d'/'| 
    rev
}

download() {
  test -z "$VERSION" && VERSION="$(last_version)"
  test -z "$VERSION" && {
    echo "Unable to get vulcan-local version." >&2
    exit 1
  }

  curl -s -L -o "$TAR_FILE" \
    "$RELEASES_URL/download/$VERSION/vulcan-local_$(uname -s)_$(uname -m).tar.gz"
}

download
tar -xf "$TAR_FILE" -C "$TMPDIR"
"${TMPDIR}/vulcan-local" "$@"
